pub struct ChartConfig {
    pub axis_width: f64,
    pub bar_gap: f64,
    pub bar_group_gap: f64,
    pub bar_stroke_width: f64,
    pub bottom_padding: f64,
    pub feature_contributions_arrow_depth: f64,
    pub feature_contributions_bar_gap: f64,
    pub feature_contributions_series_gap: f64,
    pub feature_contributions_series_height: f64,
    pub feature_contributions_default_negative_color: &'static str,
    pub feature_contributions_default_positive_color: &'static str,
    pub font: &'static str,
    pub font_size: f64,
    pub label_padding: f64,
    pub left_padding: f64,
    pub max_corner_radius: f64,
    pub point_halo_radius: f64,
    pub point_radius: f64,
    pub right_padding: f64,
    pub spline_tension: f64,
    pub tooltip_border_radius: f64,
    pub tooltip_padding: f64,
    pub tooltip_shadow_blur: f64,
    pub tooltip_target_radius: f64,
    pub top_padding: f64,
}
